# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0008_auto_20171206_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='albums', to='imager_images.Photo'),
        ),
    ]
